### ISSUE TITLE
-s instead of --search

### ISSUE THREAD

**Issue by chrisgrieser** [wayneyaoo/alfred-cheat#22]
just for the sake of quickness, could you add `-s` as an equivalent alternative to `--search`? would make it much quicker.

**Comment by mikemcduffie** [comment]
I'm playing around with a fork now, but the quick way is to right-click the workflow and choose 'Open in FInder'. Edit the cheat.py to replace `if sheetName=="--search"` on lines 24 and 31 with `if sheetName in ["--search", "-s"]`.

**Comment by MannyFay** [comment]
This is one of the very greatest workflow of Alfred :) Thank you so much!

By the date of now, you have to change the line `30` to:  
`if len(tokens) == 1 and (tokens[0] == "--search" or tokens[0] == "-s"):`  
and the line `45` to:  
`sheetName = None if tokens[0] in ["--search", "-s"] else tokens[0]`.

That's the way how the `-s` option works for me.

**Comment by wayneyaoo** [comment]
Hey folks sorry that I was basically inactive on this one since it's stable enough. A new release just added the short option. Thanks for suggesting and sorry for waiting for so long!
