### ISSUE TITLE
Workflow broken on Monterey 12.3

### ISSUE THREAD

**Issue by AntZoo** [wayneyaoo/alfred-cheat#26]
Apple removed Python 2 support in Monterey 12.3, and the workflow is no longer functional. A rewrite into Python 3 is needed.

**Comment by wayneyaoo** [comment]
See issue #25 

It's not that I don't want to. The base library don't want to support py3.

**Comment by AntZoo** [comment]
Oh shit. Sorry, didn't realize it was there!

**Comment by wayneyaoo** [comment]
lol no worries. Can you resolve by installing a python2? Or sending request to the base library to support py3 is the best shot. Until then I'm afraid there's not much I can do.

**Comment by AntZoo** [comment]
Yeah, I think I'll do both. :D

**Comment by JunweiZheng93** [comment]
Can you check [this](https://github.com/deanishe/alfred-workflow/issues/97#issuecomment-751307022) out? It seems that someone has forked the base library and made it compatible to python3.

**Comment by wayneyaoo** [comment]
@JunweiZheng93 Thanks I'm aware of it but as the author said that is not official solution. I'll still have to wait for the official upgrade, or until the original author no longer maintains the project I'll switch to the forked version.
