### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by dvnschmchr** [wayneyaoo/alfred-cheat#28]
hello i followed the readme but i cannot get the success message to pop up after entering `cf ~/.cheat` into my alfred box. 

am i missing a step?

this is what i did:

1. download the workflow
2. double click workflow to import into alfred
3. open the alfred search and type `cf ~/.cheat`

im on a mac m1 / os monterey version 12.3.1

**Comment by wayneyaoo** [comment]
Hey @dvnschmchr can you try again? Monterey 12.3 isn't support that that time and now we have a new release. That should work. Let me know!

**Comment by wayneyaoo** [comment]
Close as fixed.
